### ISSUE TITLE
ACC - Initial states

### ISSUE THREAD

**Issue by schillic** [verivital/ARCH-COMP2020#1]
https://github.com/verivital/ARCH-COMP2020/blob/5cd7696f0758c6bf147935d88ea96dfe30c56286/benchmarks/ACC/reachACC.m#L16-L17

The upper bound (`ub`) in dimensions 4 and 6 should be swapped:

```matlab
ub = [110; 32.2; 0; 11; 30.2; 0];
```

**Comment by mldiego** [comment]
That is right, thank you for catching that mistake! The correct specifications are in:[benchmarks/ACC/Specifications.txt](https://github.com/verivital/ARCH-COMP2020/blob/master/benchmarks/ACC/Specifications.txt)
