### ISSUE TITLE
Airplane: Why does dr go last?

### ISSUE THREAD

**Issue by cherrywoods** [verivital/ARCH-COMP2020#2]
Hi there,
the state vector of the airplane system has the order `[..., r, p, q]` as according to https://raw.githubusercontent.com/amaleki2/benchmark_closedloop_verification/master/AINNC_benchmark.pdf. 

I noticed that the derivative vector deviates from that order: 
https://github.com/verivital/ARCH-COMP2020/blob/5cd7696f0758c6bf147935d88ea96dfe30c56286/benchmarks/Airplane/dynamics.m#L79
I am wondering why this is the case. I couldn't quite find an explanation.  

Best regards,
David

**Comment by ttj** [comment]
As a note, I would suggest using the latest benchmarks from the 2021 competition, as some typos and other minor issues were corrected.

https://github.com/verivital/ARCH-COMP2021/blob/master/benchmarks/Airplane/dynamics.m

@mldiego can respond on your question about specifics of dynamics

**Comment by mldiego** [comment]
Hi David,

You are correct, dr dq and dp had been defined in an incorrect order. I just updated the dynamics accordingly (see [https://github.com/verivital/ARCH-COMP2021/blob/master/benchmarks/Airplane/dynamics.m](https://github.com/verivital/ARCH-COMP2021/blob/master/benchmarks/Airplane/dynamics.m)

Best,
Diego

**Comment by cherrywoods** [comment]
Thanks for fixing, Diego!
